title: "quinntest"
author: "quinn mchenry"
date: "3/14/23"
output: html_document

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)

```

```{r}
sids_budgets <- read_csv(here("data/sids_app_portfolio_projects.csv"))
```

```{r}
sids_budgets <- sids_budgets %>% 
  clean_names()
```


```{r}
sids_budgets_by_country <- sids_budgets %>% 
  drop_na() %>% 
  group_by(country) %>% 
  summarise(total_budgets = sum(budget_usd))
```


```{r}
sids_expenses_by_country <- sids_budgets %>% 
  drop_na() %>% 
  group_by(country) %>% 
  summarise(total_expenses = sum(expense_usd))
```



```{r}
 sdg_combos <- as.data.frame(table(sids_budgets$sd_gs))


# Syntax rename with condition
colnames(sdg_combos)[colnames(sdg_combos) == "Var1"] ="sd_gs"

```


```{r}
sdg_funding <- sids_budgets %>% 
  drop_na() %>% 
  group_by(sd_gs) %>% 
  summarise(total_buget = sum(budget_usd))
```




```{r}
sdg_combos_funding <- full_join(sdg_combos, sdg_funding, by = "sd_gs")
```

Small Assignment 

Make a barplot with sids_budget_by_country with country as the bar and total_budgets as the length of the bar - use ggplot hint "stat = "






