---
title: "Solar | Aid & Indicators"
author: "Connor Flynn"
date: "9/14/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(plotly)
library(readxl)
library(janitor)
library(sunburstR)
library(htmltools)
library(dplyr)
library(shiny)
options(scipen = 99)
```


Import Data from "Monitoring GLobal Aid with Machine Learning"

```{r, include=FALSE, results='hide'}
activity_clusters <- read_csv(here("data/activity_cluster_data.csv"))
```


```{r, include=FALSE, results='hide'}
descriptive_stats <- read_excel(here("data/descriptive_statistics_clusters.xlsx"))
```

Import Data from SIDS Data Platform - *may normalize for population*

```{r}
installed_renewable_per_capita <- read_csv(here("energy/indicator/installed_renewable_electricity_generating_capacity_watts_per_capita.csv"), skip = 1)

### IMmporting data from file path
energy_intensity_level_of_primary_energy <- read_csv(here("energy/indicator/energy_intensity_level_of_primary_energy(mejajoules_per_constant_2017_purchasisn_power_parity_GDP).csv"), skip = 1)

### IMmporting data from file path
Proportion_of_population_with_access_to_electricity <- read_csv(here("energy/indicator/Proportion_of_population_with_access_to_electricity_by_urban%.csv"), skip = 1)

international_fiancial_flows <- read_csv(here("energy/indicator/international_financial_flows.csv"), skip = 1)

```




```{r}
installed_renewable_per_capita[installed_renewable_per_capita == 'No Data'] <- NA

### New code
energy_intensity_level_of_primary_energy[energy_intensity_level_of_primary_energy == 'No Data'] <- NA

### New code
Proportion_of_population_with_access_to_electricity[Proportion_of_population_with_access_to_electricity == 'No Data'] <- NA

### New Code
international_fiancial_flows[international_fiancial_flows == 'No Data'] <- NA

```




```{r}
installed_renewable_per_capita_longer <- installed_renewable_per_capita %>% 
  mutate(across(!Year, as.character)) %>%
  pivot_longer(cols = !Year,
               names_to = "recipient_name",
               values_to = "value") %>% 
  clean_names()
```

```{r}
### Andrews implementation
energy_intensity_level_of_primary_energy <- energy_intensity_level_of_primary_energy %>% 
  mutate(across(!Year, as.character)) %>%
  pivot_longer(cols = !Year,
               names_to = "recipient_name",
               values_to = "value") %>% 
  clean_names()

Proportion_of_population_with_access_to_electricity <- Proportion_of_population_with_access_to_electricity %>% 
  mutate(across(!Year, as.character)) %>%
  pivot_longer(cols = !Year,
               names_to = "recipient_name",
               values_to = "value") %>% 
  clean_names()


international_fiancial_flows <- international_fiancial_flows %>% 
  mutate(across(!Year, as.character)) %>%
  pivot_longer(cols = !Year,
               names_to = "recipient_name",
               values_to = "value") %>% 
  clean_names()
```



Filter and Join Data from "Monitoring Global Aid with Machine Learning"




```{r, include=FALSE, results='hide'}
activity_clusters <- activity_clusters %>% 
  mutate(disbursement = USD_Disbursement * 1000000)
```

```{r, include=FALSE, results='hide'}
sids <- c('Anguilla', 'Antigua and Barbuda', 'Bahrain', 'Barbados', 'Belize', 'Cabo Verde', 'Comoros', 
             'Cook Islands', 'Dominica', 'Dominican Republic', 'Fiji', 'Grenada', 'Guinea-Bissau', 'Guyana', 
             'Haiti', 'Jamaica', 'Kiribati', 'Maldives', 'Marshall Islands', 'Mauritius', 'Micronesia', 
             'Montserrat', 'Nauru', 'Niue', 'Palau', 'Papua New Guinea', 'Saint Kitts and Nevis', 'Saint Lucia', 
             'Saint Vincent and the Grenadines', 'Samoa', 'Sao Tome and Principe', 'Seychelles', 'Solomon Islands', 
             'Suriname', 'Timor-Leste', 'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Turks and Caicos Islands', 
             'Tuvalu', 'Vanuatu')
```

```{r, include=FALSE, results='hide'}
colnames(activity_clusters)[colnames(activity_clusters) == "cluster"] ="Cluster"
```

```{r, include=FALSE, results='hide'}
activity_stats_join<- full_join(activity_clusters, descriptive_stats, by='Cluster')
```

```{r, include=FALSE, results='hide'}
activity_stats_sids<-activity_stats_join %>%
  filter(RecipientName %in% sids)
```

```{r, include=FALSE, results='hide'}
activity_stats_sids <- activity_stats_sids %>% 
  clean_names()
```

*Andrew Join Indicator and Aid Data*
Combining
```{r}
activity_stats_sids_energy <- activity_stats_sids %>% 
  filter(sector == "Energy")
```


```{r}
colnames(installed_renewable_per_capita_longer)[3] <- "Renewable_watts_per_capita" 
```


```{r}
combined_aid <- left_join(activity_stats_sids_energy, installed_renewable_per_capita_longer, by = "recipient_name")
```

```{r}
colnames(energy_intensity_level_of_primary_energy)[3] <- "Energy_intensity_level_of_primary_energy(MJ_PER_GDP_CON_PPP_USD)"

colnames(Proportion_of_population_with_access_to_electricity)[3] <- "Proportion_of_population_with_access_to_electricity"

colnames(international_fiancial_flows)[3] <- "international_financial_flow"
```

```{r}
combined_aid1 <- left_join(combined_aid, energy_intensity_level_of_primary_energy, by = "recipient_name")
```

```{r}
combined_aid2 <- left_join(combined_aid1, Proportion_of_population_with_access_to_electricity, by = "recipient_name")
```

```{r}
combined_aid3 <- left_join(combined_aid1, international_fiancial_flows, by = "recipient_name")
```


Ploting data

```{r}
ggplot(combined_aid, aes(x= Renewable_watts_per_capita, y = disbursement)) + 
  geom_point()
```



Solar Analyses

```{r}
activity_stats_sids_solar <- activity_stats_sids %>% 
  filter(topic == "Solar energy")
```


```{r}
a <- ggplot(activity_stats_sids_solar, 
       aes(x = year,
           y = disbursement,
           color = recipient_name)) +
  geom_line() +
  theme_minimal()
ggplotly(a)
```

